# Generated by Django 2.2.7 on 2019-11-15 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='год создания')),
                ('name', models.CharField(max_length=255, verbose_name='Имя машины')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя машины')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Имя машины')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления машины в систему')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uesr_owner', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин автомобиля')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Взял в аренду')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
