# Generated by Django 2.2.7 on 2019-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=2),
            preserve_default=False,
        ),
    ]
